apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-generate-todos
  namespace: todo-project
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-generator
              env:
                - name: API_URL
                  value: todo-project-backend-svc:8888
              image: pasiol/todo-generator@sha256:61429de5af9c06aab3672c016af4cd90298677c22492300424e06d3b64db8bea
              imagePullPolicy: IfNotPresent
          restartPolicy: Never