apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-mark-done
  namespace: todo-project
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-project-markdone
              env:
                - name: API_URL
                  value: todo-project-backend-svc:8888
              image: pasiol/todo-markdone@sha256:21c5528198a38b131154338703a12d5b2989e6e36b58bfcd85aff14786c65a8f
              imagePullPolicy: IfNotPresent
          restartPolicy: Never