apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-backend
  namespace: todo-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-project-backend
  template:
    metadata:
      labels:
        app: todo-project-backend
    spec:
      volumes:
        - name: env-file
          configMap:
            name: todo-db-host
            items:
              - key: env.properties
                path: ".env"
      containers:
        - name: todo-project-backend
          image: pasiol/todo-project-backend@sha256:74440d8c188ff56c2fc0e2d9c674ffd391a1b08040086981e734d7b1f8071ab2
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: NATS_URL
              value: nats://my-nats:4222
          volumeMounts:
            - mountPath: "/var/app/.env"
              name: env-file
              subPath: ".env"
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /todos/health
              port: 8888
          resources:
            limits:
              cpu: "10m"
              memory: "20Mi"