apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project-backend
  template:
    metadata:
      labels:
        app: todo-project-backend
    spec:
      containers:
        - name: backend
          image: pasiol/todo-project-backend@sha256:7f37f07ffc3dbd07d964a3493a12f919558f921532939ef93ae765272ea7d179
          env:
            - name: APP_PORT
              value: "8888"
            - name: ALLOWED_ORIGINS
              value: "*"