kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: todo-project-pvc
  namespace: todo-project
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: todo-project
  resources:
    requests:
      storage: 1Gi
  volumeName: todo-project-pv