kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: todo-project-backend-pvc
  namespace: todo-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi