apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-backend-db
  namespace: todo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project-backend-db
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-project-backend-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: postgres
        image: pasiol/postgres@sha256:bfc952e11e0202b0a55860d07b202f969da426b1447b0da21a5efdc65ea90a9f
        imagePullPolicy: IfNotPresent
        name: todo-project-backend-db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-volume-mount
          subPath: postgres
      volumes:
      - name: postgres-volume-mount
        persistentVolumeClaim:
          claimName: todo-project-backend-pvc
---