apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-project-backend-pvc
  namespace: todo-project
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: todo-project
  resources:
    requests:
      storage: 100Mi
  volumeName: todo-project-backend-pv