apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-project-backend-pv
  namespace: todo-project
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  storageClassName: todo-project
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/kube